(()=>{'use strict';
const api=async(path,options={})=>{const r=await fetch(path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Billing request failed.');return data;};
let catalog=null;
function money(p){return `${(Number(p.price_minor||0)/100).toFixed(2)} ${p.currency||'USD'}`}
function mount(){if(document.getElementById('nx-billing-launch'))return;const b=document.createElement('button');b.id='nx-billing-launch';b.textContent='Plans';b.style.cssText='position:fixed;right:18px;bottom:18px;z-index:9999;border:0;border-radius:999px;padding:11px 16px;background:#635bff;color:#fff;font:600 13px system-ui;box-shadow:0 8px 28px rgba(15,23,42,.2);cursor:pointer';b.onclick=open;document.body.appendChild(b)}
async function open(){const box=document.createElement('div');box.id='nx-billing-modal';box.style.cssText='position:fixed;inset:0;z-index:10000;background:rgba(15,23,42,.55);display:flex;align-items:center;justify-content:center;padding:18px;font-family:system-ui';box.innerHTML='<div style="background:#fff;max-width:900px;width:100%;max-height:90vh;overflow:auto;border-radius:18px;padding:24px"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2 style="margin:0">Nexauren Plans</h2><p style="color:#64748b">Manage your Website Builder subscription.</p></div><button id="nx-close" style="font-size:20px;border:0;background:none">×</button></div><div id="nx-billing-body">Loading…</div></div>';document.body.appendChild(box);document.getElementById('nx-close').onclick=()=>box.remove();try{catalog=catalog||await api('/api/billing/catalog');const account=await api('/api/billing/account');render(box,account)}catch(e){document.getElementById('nx-billing-body').innerHTML=`<p style="color:#b91c1c">${e.message}</p><p>Make sure the Builder is deployed with the shared D1 binding and the Nexauren session is available.</p>`}}
function render(box,account){const current=account.account?.plan_id||'free';const plans=(catalog.plans||[]).map(p=>{const active=p.id===current;const free=p.id==='free';return `<article style="border:1px solid ${active?'#635bff':'#e2e8f0'};border-radius:14px;padding:16px"><b>${p.name}</b>${active?'<span style="margin-left:8px;font-size:11px;color:#635bff">CURRENT</span>':''}<div style="font-size:24px;margin:8px 0">${money(p)} <small style="font-size:12px;color:#64748b">${p.billing_interval==='none'?'':`/ ${p.billing_interval}`}</small></div><div style="color:#64748b;margin-bottom:12px">Website Builder plan</div><button data-plan="${p.id}" style="border:0;border-radius:9px;padding:9px 12px;background:#635bff;color:#fff;cursor:pointer" ${active||free?'disabled':''}>${active?'Current plan':free?'Free plan':'Choose plan'}</button></article>`}).join('');document.getElementById('nx-billing-body').innerHTML=`<div style="background:#f8fafc;border-radius:12px;padding:14px;margin:16px 0"><b>Current plan:</b> ${account.account?.plan_name||'Free'}${account.subscription?.status?` · <b>Status:</b> ${account.subscription.status}`:''}${account.subscription?.next_billing_date?` · <b>Next billing:</b> ${new Date(Number(account.subscription.next_billing_date)*1000).toLocaleDateString()}`:''}</div><h3>Subscription plans</h3><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px">${plans||'<p>No plans available.</p>'}</div>`;box.querySelectorAll('[data-plan]').forEach(x=>x.onclick=()=>checkout(x.dataset.plan));}
async function checkout(id){try{const d=await api('/api/billing/checkout',{method:'POST',body:JSON.stringify({product_id:id})});if(d.checkout?.url)location.href=d.checkout.url;else throw new Error('PayPal approval URL was not returned.')}catch(e){alert(e.message)}}
window.NexaurenBilling={open,refresh:async()=>{catalog=null;open()}};document.addEventListener('DOMContentLoaded',mount);
})();
