(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='nexauren_builder_mvp_v1',uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36),types={website:'Website',blog:'Blog',store:'Store',portfolio:'Portfolio',landing:'Landing page',business:'Business'},blocks={heading:'Heading',text:'Text',image:'Image',button:'Button',spacer:'Spacer'};
let sites=[];try{sites=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{};let active=sites[0]||null,pageIndex=0,selected=null,view='home';
const persist=()=>localStorage.setItem(KEY,JSON.stringify(sites)),page=()=>active?.pages?.[pageIndex]||active?.pages?.[0];
function makeBlock(type){return type==='heading'?{id:uid(),type,text:'New heading'}:type==='text'?{id:uid(),type,text:'Write your text here.'}:type==='image'?{id:uid(),type,url:'',alt:'Image'}:type==='button'?{id:uid(),type,text:'Button',url:'#'}:{id:uid(),type,height:70}}
function createSite(type='website',name='My Website'){active={id:uid(),name:name.trim()||'My Website',type,pages:[{id:uid(),name:'Home',slug:'/',blocks:[{id:uid(),type:'heading',text:'Welcome to my website'},{id:uid(),type:'text',text:'Tell visitors what your website is about.'},{id:uid(),type:'button',text:'Get started',url:'#'}]}],createdAt:Date.now(),updatedAt:Date.now()};sites=[active,...sites];persist();pageIndex=0;selected=null;view='home';render()}
function render(){document.title=active?active.name+' — Nexauren':'Nexauren Website Builder';$('#app').innerHTML=active?app():start();bind()}
function start(){return `<div class="start"><div class="brand">N<span>×</span> Nexauren</div><div class="start-card"><div class="eyebrow">WEBSITE BUILDER</div><h1>Create your website.</h1><p>Start with the basics. No complicated builder.</p><button class="primary big" data-create>Create website</button><div class="templates">${Object.entries(types).map(([k,v])=>`<button class="template" data-type="${k}"><b>${v}</b><small>Start with a simple ${v.toLowerCase()}</small></button>`).join('')}</div></div></div>`}
function app(){let body=view==='pages'?pagesView():view==='builder'?(selected?editor():builder()):view==='account'?account():home();return `<div class="shell"><aside class="side"><div class="brand">N<span>×</span> Nexauren</div><div class="site-card"><small>MY WEBSITE</small><b>${esc(active.name)}</b><span>${esc(types[active.type]||'Website')}</span></div><nav><button class="${view==='home'?'active':''}" data-view="home">⌂ Home</button><button class="${view==='pages'?'active':''}" data-view="pages">▤ Pages</button><button class="${view==='builder'?'active':''}" data-view="builder">✎ Website</button><button class="${view==='account'?'active':''}" data-view="account">◎ My Account</button></nav><button class="new-site" data-new>＋ New website</button></aside><main class="main"><header><div><strong>${view==='builder'?esc(page()?.name||'Home'):view==='pages'?'Pages':view==='account'?'My Account':'Home'}</strong><span class="muted"> / ${esc(active.name)}</span></div><div class="actions">${view==='builder'?'<button data-save>Save</button><button data-preview>Preview</button><button class="primary" data-publish>Publish</button>':''}</div></header><section class="content">${body}</section></main></div>`}
function home(){return `<div class="hero"><div><h1>${esc(active.name)}</h1><p>Create pages, add content, save and preview.</p></div><button class="primary" data-view="builder">Open website editor</button></div><div class="cards"><div><b>${active.pages.length}</b><span>Pages</span></div><div><b>${page()?.blocks.length||0}</b><span>Blocks</span></div><div><b>${types[active.type]||'Website'}</b><span>Type</span></div></div><div class="panel"><h2>How to build</h2><div class="steps"><p><b>1. Pages</b><br>Add Home, About, Contact or any page.</p><p><b>2. Website</b><br>Add Heading, Text, Image, Button or Spacer. Click a block to edit.</p><p><b>3. Save & Preview</b><br>Save your work and preview the page.</p></div></div>`}
function pagesView(){return `<div class="title-row"><div><h1>Pages</h1><p class="muted">Simple page management.</p></div><button class="primary" data-add-page>＋ Add page</button></div><div class="panel">${active.pages.map((p,i)=>`<div class="page-row"><div><b>${esc(p.name)}</b><small>${esc(p.slug)}</small></div><div><button data-open-page="${i}">Edit</button>${active.pages.length>1?`<button class="danger" data-delete-page="${i}">Delete</button>`:''}</div></div>`).join('')}</div>`}
function builder(){return `<div class="title-row"><div><h1>${esc(page().name)}</h1><p class="muted">Add a block, then click it to edit.</p></div></div><div class="builder"><aside class="blockbar"><h3>Add block</h3>${Object.entries(blocks).map(([k,v])=>`<button data-add-block="${k}"><b>${v}</b><small>Simple block</small></button>`).join('')}</aside><div class="canvas"><div class="site-page">${renderPage()}</div></div></div>`}
function renderPage(){return page().blocks.map(b=>{const s=selected===b.id?' selected':'';if(b.type==='heading')return `<section class="block heading${s}" data-select="${b.id}"><h1>${esc(b.text)}</h1></section>`;if(b.type==='text')return `<section class="block text${s}" data-select="${b.id}"><p>${esc(b.text)}</p></section>`;if(b.type==='image')return `<section class="block image${s}" data-select="${b.id}">${b.url?`<img src="${esc(b.url)}" alt="${esc(b.alt)}">`:'<div class="image-empty">Image — click to add URL</div>'}</section>`;if(b.type==='button')return `<section class="block button-block${s}" data-select="${b.id}"><a href="${esc(b.url)}">${esc(b.text)}</a></section>`;return `<section class="block spacer${s}" data-select="${b.id}" style="height:${Math.max(20,Number(b.height)||70)}px"></section>`}).join('')}
function editor(){const b=page().blocks.find(x=>x.id===selected);return `<div class="editor-layout"><div class="panel edit-panel"><div class="title-row"><div><h2>Edit ${blocks[b.type]}</h2><p class="muted">Only the essentials.</p></div><button data-close-edit>×</button></div>${b.type==='image'?`<label>Image URL<input data-field="url" value="${esc(b.url)}" placeholder="https://..."></label><label>Alt text<input data-field="alt" value="${esc(b.alt)}"></label>`:b.type==='spacer'?`<label>Height<input type="number" data-field="height" value="${Number(b.height)||70}"></label>`:`<label>Text<textarea data-field="text">${esc(b.text)}</textarea></label>${b.type==='button'?`<label>Link<input data-field="url" value="${esc(b.url)}"></label>`:''}`}<div class="edit-actions"><button class="primary" data-done>Done</button><button class="danger" data-remove>Delete block</button></div></div><div class="preview-mini"><div class="site-page">${renderPage()}</div></div></div>`}
function account(){return `<div class="title-row"><div><h1>My Account</h1><p class="muted">Account and Website Builder subscription.</p></div><button data-plans>Manage plans</button></div><div class="account-grid"><div class="panel"><h2>Account</h2><p id="account-email">Loading account…</p><p class="muted">Websites saved on this device: ${sites.length}</p></div><div class="panel"><h2>Subscription</h2><p id="account-plan">Loading subscription…</p><button class="primary" data-plans>View plans</button></div></div>`}
function bind(){document.querySelectorAll('[data-type]').forEach(x=>x.onclick=()=>{const n=prompt('Website name','My Website');if(n!==null)createSite(x.dataset.type,n)});const c=$('[data-create]');if(c)c.onclick=()=>{const n=prompt('Website name','My Website');if(n!==null)createSite('website',n)};const n=$('[data-new]');if(n)n.onclick=()=>{const name=prompt('Website name','My Website');if(name!==null)createSite('website',name)};document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>{view=x.dataset.view;selected=null;render()});document.querySelectorAll('[data-open-page]').forEach(x=>x.onclick=()=>{pageIndex=+x.dataset.openPage;view='builder';selected=null;render()});const ap=$('[data-add-page]');if(ap)ap.onclick=addPage;document.querySelectorAll('[data-delete-page]').forEach(x=>x.onclick=()=>{if(confirm('Delete this page?')){active.pages.splice(+x.dataset.deletePage,1);pageIndex=Math.max(0,pageIndex-1);save();render()}});document.querySelectorAll('[data-add-block]').forEach(x=>x.onclick=()=>{page().blocks.push(makeBlock(x.dataset.addBlock));save();render()});document.querySelectorAll('[data-select]').forEach(x=>x.onclick=()=>{selected=x.dataset.select;render()});const ce=$('[data-close-edit]');if(ce)ce.onclick=()=>{selected=null;render()};const done=$('[data-done]');if(done)done.onclick=()=>{selected=null;save();render()};document.querySelectorAll('[data-field]').forEach(x=>x.oninput=()=>{const b=page().blocks.find(v=>v.id===selected);if(b){b[x.dataset.field]=x.type==='number'?+x.value:x.value;persist()}});const rm=$('[data-remove]');if(rm)rm.onclick=()=>{page().blocks=page().blocks.filter(x=>x.id!==selected);selected=null;save();render()};const sv=$('[data-save]');if(sv)sv.onclick=save;const pr=$('[data-preview]');if(pr)pr.onclick=preview;const pu=$('[data-publish]');if(pu)pu.onclick=()=>{save();toast('Site saved. Publishing connection will be added next.')};document.querySelectorAll('[data-plans]').forEach(x=>x.onclick=()=>window.NexaurenBilling?.open())}
function addPage(){const n=prompt('Page name','About');if(!n)return;const slug='/'+n.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');active.pages.push({id:uid(),name:n,slug,blocks:[{id:uid(),type:'heading',text:n},{id:uid(),type:'text',text:'Add your content here.'}]});pageIndex=active.pages.length-1;view='builder';selected=null;save();render()}
function preview(){const w=window.open('','_blank');if(!w)return;w.document.write(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(active.name)}</title><style>body{font-family:system-ui;margin:0;color:#172033}.site{max-width:900px;margin:auto}.block{padding:30px 24px}.heading{text-align:center;padding-top:80px}.heading h1{font-size:48px}.text{font-size:18px;line-height:1.7}.image img{max-width:100%;display:block;margin:auto}.button-block{text-align:center}.button-block a{display:inline-block;background:#635bff;color:#fff;padding:12px 18px;border-radius:9px;text-decoration:none;font-weight:700}.image-empty{padding:80px;background:#f1f5f9;text-align:center;color:#64748b}</style></head><body><main class="site">${renderPage()}</main></body></html>`);w.document.close()}
async function loadAccount(){try{const r=await fetch('/api/account',{credentials:'include'}),d=await r.json();const e=$('#account-email');if(e)e.textContent=d.user?.email||'Signed in';const r2=await fetch('/api/billing/account',{credentials:'include'}),a=await r2.json();const p=$('#account-plan');if(p)p.textContent=`${a.account?.plan_name||'Free'} · ${a.subscription?.status||'active'}`}catch{const e=$('#account-email');if(e)e.textContent='Sign in to see your account details.'}}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
if(view==='account')setTimeout(loadAccount,0);render();
})();
