const Editor=(()=>{
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const api=async(path,options={})=>{const r=await fetch(path,{credentials:'include',cache:'no-store',...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Erro ${r.status}`);return d};
  const types=[['hero','Hero'],['text','Texto'],['image','Imagem'],['button','Botão'],['features','Funcionalidades'],['faq','FAQ'],['pricing','Preços'],['gallery','Galeria'],['cta','CTA'],['spacer','Espaço']];
  const variants={hero:['center','split-image-right','split-image-left'],text:['center','left','two-column'],image:['full','contained','rounded'],button:['solid','outline','link'],features:['three','four','bento'],faq:['accordion','two-column'],pricing:['three','featured'],gallery:['grid','two-column'],cta:['center','split'],spacer:['small','medium','large']};
  const defaults={hero:{title:'Crie algo incrível',description:'Apresente o seu projeto com uma mensagem clara.',button:'Começar agora',button_url:'#'},text:{title:'Título da secção',body:'Escreva o seu conteúdo aqui.'},image:{title:'Uma imagem',url:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80',alt:'Imagem do website'},button:{label:'Saiba mais',url:'#'},features:{title:'O que oferecemos',items:['Primeiro benefício','Segundo benefício','Terceiro benefício']},faq:{title:'Perguntas frequentes',items:[{question:'Qual é a sua pergunta?',answer:'Escreva a resposta aqui.'}]},pricing:{title:'Planos',items:[{name:'Plano',price:'0',description:'Descrição do plano',button:'Escolher'}]},gallery:{title:'Galeria',images:['https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=80']},cta:{title:'Pronto para começar?',body:'Convide o visitante a dar o próximo passo.',button:'Começar'},spacer:{height:80}};
  let project=null,page=null,sections=[],selected=null,dirty=false;
  const clone=o=>JSON.parse(JSON.stringify(o));
  const hashSlug=()=>decodeURIComponent((location.hash.match(/^#\/editor\/([^?]+)/)||[])[1]||'');
  const app=()=>document.querySelector('#app');
  const toast=(msg,error=false)=>{let x=document.querySelector('#editor-toast');if(!x){x=document.createElement('div');x.id='editor-toast';document.body.appendChild(x)}x.textContent=msg;x.className=`editor-toast ${error?'error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>x.remove(),2600)};
  const field=(label,key,value,area=false)=>`<label class="editor-field"><span>${label}</span>${area?`<textarea data-key="${key}" rows="5">${esc(value)}</textarea>`:`<input data-key="${key}" value="${esc(value)}">`}</label>`;
  function contentFields(s){const c=s.content||{};if(s.type==='hero')return field('Título','title',c.title)+field('Descrição','description',c.description,true)+field('Texto do botão','button',c.button)+field('URL do botão','button_url',c.button_url);if(s.type==='text')return field('Título','title',c.title)+field('Conteúdo','body',c.body,true);if(s.type==='image')return field('Título','title',c.title)+field('URL da imagem','url',c.url)+field('Texto alternativo','alt',c.alt);if(s.type==='button')return field('Texto','label',c.label)+field('URL','url',c.url);if(s.type==='cta')return field('Título','title',c.title)+field('Texto','body',c.body,true)+field('Botão','button',c.button);if(s.type==='spacer')return field('Altura (px)','height',c.height);if(['features','faq','pricing','gallery'].includes(s.type))return `<label class="editor-field"><span>Conteúdo JSON</span><textarea data-key="__json" rows="12">${esc(JSON.stringify(c,null,2))}</textarea></label><p class="editor-help">Edite o conteúdo da secção em JSON. A estrutura inicial já vem preenchida.</p>`;return field('Conteúdo','body',c.body||'');}
  function preview(s){const c=s.content||{};let h='';if(s.type==='hero')h=`<section class="pv hero ${esc(s.variant)}"><div><h1>${esc(c.title)}</h1><p>${esc(c.description)}</p>${c.button?`<a>${esc(c.button)}</a>`:''}</div></section>`;else if(s.type==='text')h=`<section class="pv text"><h2>${esc(c.title)}</h2><p>${esc(c.body)}</p></section>`;else if(s.type==='image')h=`<section class="pv image"><h2>${esc(c.title)}</h2><img src="${esc(c.url)}" alt="${esc(c.alt)}" loading="lazy"><small>${esc(c.url)}</small></section>`;else if(s.type==='button')h=`<section class="pv button"><a>${esc(c.label)}</a><small>${esc(c.url)}</small></section>`;else if(s.type==='features')h=`<section class="pv"><h2>${esc(c.title)}</h2><div class="pv-grid">${(c.items||[]).map(x=>`<article><b>${esc(x)}</b><p>Descrição da funcionalidade.</p></article>`).join('')}</div></section>`;else if(s.type==='faq')h=`<section class="pv"><h2>${esc(c.title)}</h2>${(c.items||[]).map(x=>`<details open><summary>${esc(x.question)}</summary><p>${esc(x.answer)}</p></details>`).join('')}</section>`;else if(s.type==='pricing')h=`<section class="pv"><h2>${esc(c.title)}</h2><div class="pv-grid">${(c.items||[]).map(x=>`<article><h3>${esc(x.name)}</h3><strong>${esc(x.price)}</strong><p>${esc(x.description)}</p><a>${esc(x.button)}</a></article>`).join('')}</div></section>`;else if(s.type==='gallery')h=`<section class="pv"><h2>${esc(c.title)}</h2><div class="pv-gallery">${(c.images||[]).map(x=>`<img src="${esc(x)}" loading="lazy">`).join('')}</div></section>`;else if(s.type==='cta')h=`<section class="pv cta"><h2>${esc(c.title)}</h2><p>${esc(c.body)}</p><a>${esc(c.button)}</a></section>`;else h=`<section class="pv spacer" style="height:${Math.max(20,Math.min(500,Number(c.height)||80))}px"><span>Espaço</span></section>`;return `<div class="preview-section ${selected?.id===s.id?'is-selected':''}" data-select="${esc(s.id)}"><div class="preview-actions"><button data-up="${esc(s.id)}" title="Subir">↑</button><button data-down="${esc(s.id)}" title="Descer">↓</button><button data-duplicate="${esc(s.id)}" title="Duplicar">⧉</button><button data-delete="${esc(s.id)}" title="Apagar">×</button></div>${h}</div>`;}
  function render(){if(!app())return;app().innerHTML=`<div class="editor-app"><header class="editor-bar"><div class="editor-brand"><a href="#/dashboard">← Dashboard</a><strong>${esc(project?.name||'Website')}</strong><span>${dirty?'Alterações por guardar':'Guardado'}</span></div><div class="editor-bar-actions"><button class="editor-btn" id="preview-site">Pré-visualizar</button><button class="editor-btn primary" id="save-site" ${dirty?'':'disabled'}>Guardar</button></div></header><div class="editor-workspace"><aside class="editor-sidebar left"><div class="editor-sidebar-title"><strong>Secções</strong><button id="add-section">+ Adicionar</button></div><div class="section-list">${sections.length?sections.map((s,i)=>`<button class="section-item ${selected?.id===s.id?'selected':''}" data-select="${esc(s.id)}"><span>${i+1}</span><b>${esc(types.find(x=>x[0]===s.type)?.[1]||s.type)}</b><small>${esc(s.variant||'default')}</small></button>`).join(''):'<div class="editor-empty">Ainda não há secções.<br>Adicione a primeira.</div>'}</div></aside><main class="editor-canvas"><div class="canvas-head"><span>Home</span><div><button data-device="desktop" class="device active">Desktop</button><button data-device="mobile" class="device">Mobile</button></div></div><div class="site-preview" id="site-preview">${sections.length?sections.map(preview).join(''):`<div class="preview-empty"><h2>O seu website começa aqui</h2><p>Adicione uma secção no painel esquerdo.</p></div>`}</div></main><aside class="editor-sidebar right">${selected?`<div class="editor-sidebar-title"><strong>Editar secção</strong><button id="close-properties">×</button></div><div class="editor-properties"><div class="editor-field"><span>Tipo</span><select disabled>${types.map(x=>`<option ${x[0]===selected.type?'selected':''}>${esc(x[1])}</option>`).join('')}</select></div><label class="editor-field"><span>Layout</span><select id="variant-select">${(variants[selected.type]||['default']).map(v=>`<option value="${esc(v)}" ${v===selected.variant?'selected':''}>${esc(v)}</option>`).join('')}</select></label>${contentFields(selected)}<button class="editor-btn primary full" id="apply-section">Aplicar alterações</button></div>`:`<div class="editor-inspector-empty"><strong>Selecione uma secção</strong><p>Escolha uma secção no canvas para editar o conteúdo e o layout.</p></div>`}</aside></div></div>`;bind();}
  function bind(){document.querySelectorAll('[data-select]').forEach(x=>x.onclick=()=>{selected=sections.find(s=>s.id===x.dataset.select)||null;render()});document.querySelectorAll('[data-up]').forEach(x=>x.onclick=e=>move(x.dataset.up,-1));document.querySelectorAll('[data-down]').forEach(x=>x.onclick=e=>move(x.dataset.down,1));document.querySelectorAll('[data-duplicate]').forEach(x=>x.onclick=()=>duplicate(x.dataset.duplicate));document.querySelectorAll('[data-delete]').forEach(x=>x.onclick=()=>remove(x.dataset.delete));document.querySelector('#close-properties')?.addEventListener('click',()=>{selected=null;render()});document.querySelector('#add-section')?.addEventListener('click',addMenu);document.querySelector('#save-site')?.addEventListener('click',saveAll);document.querySelector('#preview-site')?.addEventListener('click',()=>window.open(`/preview/${encodeURIComponent(project.slug)}`,'_blank'));document.querySelector('#apply-section')?.addEventListener('click',applySelected);document.querySelector('#variant-select')?.addEventListener('change',e=>{selected.variant=e.target.value;dirty=true;render()});document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-device]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#site-preview')?.classList.toggle('mobile-preview',b.dataset.device==='mobile')});}
  function addMenu(){const wrap=document.createElement('div');wrap.className='editor-modal';wrap.innerHTML=`<div class="editor-modal-card"><div class="editor-sidebar-title"><strong>Adicionar secção</strong><button id="close-add">×</button></div><div class="add-grid">${types.map(([id,name])=>`<button data-add-type="${id}"><b>${name}</b><small>${(variants[id]||['default']).length} layouts</small></button>`).join('')}</div></div>`;document.body.appendChild(wrap);wrap.querySelector('#close-add').onclick=()=>wrap.remove();wrap.querySelectorAll('[data-add-type]').forEach(b=>b.onclick=async()=>{await addSection(b.dataset.addType);wrap.remove()});}
  async function addSection(type){try{const d=await api(`/api/editor/sections?page_id=${encodeURIComponent(page.id)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type,variant:(variants[type]||['default'])[0],content:clone(defaults[type])})});sections.push(d.section);selected=d.section;dirty=false;render();toast('Secção adicionada.')}catch(e){toast(e.message,true)}}
  function readSelected(){const c=clone(selected.content||{});document.querySelectorAll('[data-key]').forEach(el=>{const k=el.dataset.key;if(k==='__json')return;c[k]=el.value});const j=document.querySelector('[data-key="__json"]');if(j){try{Object.assign(c,JSON.parse(j.value))}catch{throw new Error('O conteúdo JSON não é válido.')}}return c;}
  async function applySelected(){try{selected.content=readSelected();await api(`/api/editor/sections?page_id=${encodeURIComponent(page.id)}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:selected.id,variant:selected.variant,sort_order:selected.sort_order,content:selected.content,style:selected.style||{}})});dirty=false;render();toast('Secção guardada.')}catch(e){toast(e.message,true)}}
  async function saveAll(){try{for(let i=0;i<sections.length;i++){sections[i].sort_order=i;await api(`/api/editor/sections?page_id=${encodeURIComponent(page.id)}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:sections[i].id,variant:sections[i].variant,sort_order:i,content:sections[i].content,style:sections[i].style||{}})})}dirty=false;render();toast('Todas as alterações foram guardadas.')}catch(e){toast(e.message,true)}}
  function move(id,delta){const i=sections.findIndex(s=>s.id===id),j=i+delta;if(i<0||j<0||j>=sections.length)return;[sections[i],sections[j]]=[sections[j],sections[i]];sections.forEach((s,k)=>s.sort_order=k);dirty=true;selected=sections[j];render();}
  async function duplicate(id){const s=sections.find(x=>x.id===id);if(!s)return;try{const d=await api(`/api/editor/sections?page_id=${encodeURIComponent(page.id)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:s.type,variant:s.variant,content:clone(s.content)})});sections.push(d.section);dirty=true;selected=d.section;render();toast('Secção duplicada.')}catch(e){toast(e.message,true)}}
  async function remove(id){const s=sections.find(x=>x.id===id);if(!s||!confirm('Apagar esta secção?'))return;try{await api(`/api/editor/sections?page_id=${encodeURIComponent(page.id)}&id=${encodeURIComponent(id)}`,{method:'DELETE'});sections=sections.filter(x=>x.id!==id);selected=sections[0]||null;dirty=false;render();toast('Secção apagada.')}catch(e){toast(e.message,true)}}
  async function open(){const slug=hashSlug();if(!slug)return;try{const u=await api('/api/auth/me').catch(()=>null);if(!u?.authenticated){location.hash=`#/auth?next=${encodeURIComponent(`#/editor/${slug}`)}`;return}const d=await api(`/api/editor/project?slug=${encodeURIComponent(slug)}`);project=d.project;page=(d.pages||[])[0];if(!page)throw new Error('Este website ainda não tem uma página inicial.');const s=await api(`/api/editor/sections?page_id=${encodeURIComponent(page.id)}`);sections=s.sections||[];selected=sections[0]||null;dirty=false;render();}catch(e){if(app())app().innerHTML=`<section class="editor-error"><h1>Não foi possível abrir o editor.</h1><p>${esc(e.message)}</p><a class="editor-btn primary" href="#/dashboard">Voltar ao Dashboard</a></section>`}}
  function hookDashboard(){const root=document.querySelector('#app');if(!root)return;const observer=new MutationObserver(()=>{document.querySelectorAll('.project-card').forEach(card=>{const btn=card.querySelector('.project-actions .btn.primary');if(!btn||btn.dataset.editorReady)return;const m=(card.querySelector('.muted')?.textContent||'').match(/^\/([^·\s]+)/);if(!m)return;btn.dataset.editorReady='1';btn.disabled=false;btn.textContent='Abrir editor';btn.onclick=()=>location.hash=`#/editor/${encodeURIComponent(m[1])}`;const secondary=card.querySelector('.project-actions .btn.secondary');if(secondary)secondary.remove()})});observer.observe(root,{childList:true,subtree:true});}
  window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#/editor/'))open()});
  hookDashboard();
  if(location.hash.startsWith('#/editor/'))open();
})();